default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: germina_development
  username: root
  password: '123456'
  host: localhost

test:
  <<: *default
  database: germina_test
  username: root
  password: '123456'
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
